# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'erp.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QMainWindow, QMenu,
    QMenuBar, QPushButton, QSizePolicy, QWidget)
import ui.icons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(822, 301)
        self.actionCliente = QAction(MainWindow)
        self.actionCliente.setObjectName(u"actionCliente")
        self.actionFornecedor = QAction(MainWindow)
        self.actionFornecedor.setObjectName(u"actionFornecedor")
        self.actionUsuarios = QAction(MainWindow)
        self.actionUsuarios.setObjectName(u"actionUsuarios")
        self.actionVenda = QAction(MainWindow)
        self.actionVenda.setObjectName(u"actionVenda")
        self.actionConsumo_de_produtos = QAction(MainWindow)
        self.actionConsumo_de_produtos.setObjectName(u"actionConsumo_de_produtos")
        self.actionSaldo = QAction(MainWindow)
        self.actionSaldo.setObjectName(u"actionSaldo")
        self.actionCompras_2 = QAction(MainWindow)
        self.actionCompras_2.setObjectName(u"actionCompras_2")
        self.actionPedido = QAction(MainWindow)
        self.actionPedido.setObjectName(u"actionPedido")
        self.actionCancelar_compra = QAction(MainWindow)
        self.actionCancelar_compra.setObjectName(u"actionCancelar_compra")
        self.actionCaixa = QAction(MainWindow)
        self.actionCaixa.setObjectName(u"actionCaixa")
        self.actionContas_bancos = QAction(MainWindow)
        self.actionContas_bancos.setObjectName(u"actionContas_bancos")
        self.actionContas_pagar = QAction(MainWindow)
        self.actionContas_pagar.setObjectName(u"actionContas_pagar")
        self.actionContas_pagas = QAction(MainWindow)
        self.actionContas_pagas.setObjectName(u"actionContas_pagas")
        self.actionContas_receber = QAction(MainWindow)
        self.actionContas_receber.setObjectName(u"actionContas_receber")
        self.actionContas_recebidas = QAction(MainWindow)
        self.actionContas_recebidas.setObjectName(u"actionContas_recebidas")
        self.actionGeral = QAction(MainWindow)
        self.actionGeral.setObjectName(u"actionGeral")
        self.actionResumido = QAction(MainWindow)
        self.actionResumido.setObjectName(u"actionResumido")
        self.actionGeral_2 = QAction(MainWindow)
        self.actionGeral_2.setObjectName(u"actionGeral_2")
        self.actionResumido_2 = QAction(MainWindow)
        self.actionResumido_2.setObjectName(u"actionResumido_2")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lbl_logo = QLabel(self.centralwidget)
        self.lbl_logo.setObjectName(u"lbl_logo")
        self.lbl_logo.setGeometry(QRect(290, 100, 231, 151))
        self.lbl_logo.setStyleSheet(u"image: url(:/logo_empresa/logo_empresa.png);")
        self.btn_cliente = QPushButton(self.centralwidget)
        self.btn_cliente.setObjectName(u"btn_cliente")
        self.btn_cliente.setGeometry(QRect(10, 0, 81, 81))
        self.btn_cliente.setStyleSheet(u"image: url(:/icon_cliente/cliente.png);")
        self.btn_fornecedor = QPushButton(self.centralwidget)
        self.btn_fornecedor.setObjectName(u"btn_fornecedor")
        self.btn_fornecedor.setGeometry(QRect(100, 0, 81, 81))
        self.btn_fornecedor.setStyleSheet(u"image: url(:/icon_fornecedor/fornecedor.png);")
        self.btn_vendas = QPushButton(self.centralwidget)
        self.btn_vendas.setObjectName(u"btn_vendas")
        self.btn_vendas.setGeometry(QRect(280, 0, 81, 81))
        self.btn_vendas.setStyleSheet(u"image: url(:/icon_vendas/venda.png);")
        self.btn_produtos = QPushButton(self.centralwidget)
        self.btn_produtos.setObjectName(u"btn_produtos")
        self.btn_produtos.setGeometry(QRect(190, 0, 81, 81))
        self.btn_produtos.setStyleSheet(u"image: url(:/icon_produtos/produtos.png);")
        self.btn_receber = QPushButton(self.centralwidget)
        self.btn_receber.setObjectName(u"btn_receber")
        self.btn_receber.setGeometry(QRect(550, 0, 81, 81))
        self.btn_receber.setStyleSheet(u"image: url(:/icon_receber/receber.png)")
        self.btn_bancos = QPushButton(self.centralwidget)
        self.btn_bancos.setObjectName(u"btn_bancos")
        self.btn_bancos.setGeometry(QRect(460, 0, 81, 81))
        self.btn_bancos.setStyleSheet(u"image: url(:/icon_banco/banco.png);")
        self.btn_pagar = QPushButton(self.centralwidget)
        self.btn_pagar.setObjectName(u"btn_pagar")
        self.btn_pagar.setGeometry(QRect(370, 0, 81, 81))
        self.btn_pagar.setStyleSheet(u"image: url(:/icon_pagar/contasPagar.png);")
        self.btn_caixa = QPushButton(self.centralwidget)
        self.btn_caixa.setObjectName(u"btn_caixa")
        self.btn_caixa.setGeometry(QRect(640, 0, 81, 81))
        self.btn_caixa.setStyleSheet(u"image: url(:/icon_caixa/caixa.png)")
        self.btn_sair = QPushButton(self.centralwidget)
        self.btn_sair.setObjectName(u"btn_sair")
        self.btn_sair.setGeometry(QRect(730, 0, 81, 81))
        self.btn_sair.setStyleSheet(u"image: url(:/icon_sair/sair.png)")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 822, 24))
        self.menuCadastros = QMenu(self.menubar)
        self.menuCadastros.setObjectName(u"menuCadastros")
        self.menuOpera_es = QMenu(self.menubar)
        self.menuOpera_es.setObjectName(u"menuOpera_es")
        self.menuSaida_de_produtos = QMenu(self.menuOpera_es)
        self.menuSaida_de_produtos.setObjectName(u"menuSaida_de_produtos")
        self.menuEstoque = QMenu(self.menuOpera_es)
        self.menuEstoque.setObjectName(u"menuEstoque")
        self.menuCompras = QMenu(self.menuOpera_es)
        self.menuCompras.setObjectName(u"menuCompras")
        self.menuFinanceiro = QMenu(self.menubar)
        self.menuFinanceiro.setObjectName(u"menuFinanceiro")
        self.menuConsultas = QMenu(self.menubar)
        self.menuConsultas.setObjectName(u"menuConsultas")
        self.menuVendas = QMenu(self.menuConsultas)
        self.menuVendas.setObjectName(u"menuVendas")
        self.menuConsumos = QMenu(self.menuConsultas)
        self.menuConsumos.setObjectName(u"menuConsumos")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuCadastros.menuAction())
        self.menubar.addAction(self.menuOpera_es.menuAction())
        self.menubar.addAction(self.menuFinanceiro.menuAction())
        self.menubar.addAction(self.menuConsultas.menuAction())
        self.menuCadastros.addAction(self.actionCliente)
        self.menuCadastros.addAction(self.actionFornecedor)
        self.menuCadastros.addAction(self.actionUsuarios)
        self.menuOpera_es.addAction(self.menuSaida_de_produtos.menuAction())
        self.menuOpera_es.addAction(self.menuEstoque.menuAction())
        self.menuOpera_es.addAction(self.menuCompras.menuAction())
        self.menuSaida_de_produtos.addAction(self.actionVenda)
        self.menuSaida_de_produtos.addAction(self.actionConsumo_de_produtos)
        self.menuEstoque.addAction(self.actionSaldo)
        self.menuCompras.addAction(self.actionCompras_2)
        self.menuCompras.addAction(self.actionPedido)
        self.menuCompras.addAction(self.actionCancelar_compra)
        self.menuFinanceiro.addAction(self.actionCaixa)
        self.menuFinanceiro.addAction(self.actionContas_bancos)
        self.menuFinanceiro.addAction(self.actionContas_pagar)
        self.menuFinanceiro.addAction(self.actionContas_pagas)
        self.menuFinanceiro.addAction(self.actionContas_receber)
        self.menuFinanceiro.addAction(self.actionContas_recebidas)
        self.menuConsultas.addAction(self.menuVendas.menuAction())
        self.menuConsultas.addAction(self.menuConsumos.menuAction())
        self.menuVendas.addAction(self.actionGeral)
        self.menuVendas.addAction(self.actionResumido)
        self.menuConsumos.addAction(self.actionGeral_2)
        self.menuConsumos.addAction(self.actionResumido_2)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionCliente.setText(QCoreApplication.translate("MainWindow", u"Cliente", None))
        self.actionFornecedor.setText(QCoreApplication.translate("MainWindow", u"Fornecedor", None))
        self.actionUsuarios.setText(QCoreApplication.translate("MainWindow", u"Usuarios", None))
        self.actionVenda.setText(QCoreApplication.translate("MainWindow", u"Venda", None))
        self.actionConsumo_de_produtos.setText(QCoreApplication.translate("MainWindow", u"Consumo de produtos", None))
        self.actionSaldo.setText(QCoreApplication.translate("MainWindow", u"Saldo", None))
        self.actionCompras_2.setText(QCoreApplication.translate("MainWindow", u"Comprar", None))
        self.actionPedido.setText(QCoreApplication.translate("MainWindow", u"Pedido", None))
        self.actionCancelar_compra.setText(QCoreApplication.translate("MainWindow", u"Cancelar compra", None))
        self.actionCaixa.setText(QCoreApplication.translate("MainWindow", u"Caixa", None))
        self.actionContas_bancos.setText(QCoreApplication.translate("MainWindow", u"Contas bancos", None))
        self.actionContas_pagar.setText(QCoreApplication.translate("MainWindow", u"Contas pagar", None))
        self.actionContas_pagas.setText(QCoreApplication.translate("MainWindow", u"Contas pagas", None))
        self.actionContas_receber.setText(QCoreApplication.translate("MainWindow", u"Contas receber", None))
        self.actionContas_recebidas.setText(QCoreApplication.translate("MainWindow", u"Contas recebidas", None))
        self.actionGeral.setText(QCoreApplication.translate("MainWindow", u"Geral", None))
        self.actionResumido.setText(QCoreApplication.translate("MainWindow", u"Resumido", None))
        self.actionGeral_2.setText(QCoreApplication.translate("MainWindow", u"Geral", None))
        self.actionResumido_2.setText(QCoreApplication.translate("MainWindow", u"Resumido", None))
        self.lbl_logo.setText("")
        self.btn_cliente.setText("")
        self.btn_fornecedor.setText("")
        self.btn_vendas.setText("")
        self.btn_produtos.setText("")
        self.btn_receber.setText("")
        self.btn_bancos.setText("")
        self.btn_pagar.setText("")
        self.btn_caixa.setText("")
        self.btn_sair.setText("")
        self.menuCadastros.setTitle(QCoreApplication.translate("MainWindow", u"Cadastros", None))
        self.menuOpera_es.setTitle(QCoreApplication.translate("MainWindow", u"Opera\u00e7\u00f5es", None))
        self.menuSaida_de_produtos.setTitle(QCoreApplication.translate("MainWindow", u"Saida de produtos", None))
        self.menuEstoque.setTitle(QCoreApplication.translate("MainWindow", u"Estoque", None))
        self.menuCompras.setTitle(QCoreApplication.translate("MainWindow", u"Compras", None))
        self.menuFinanceiro.setTitle(QCoreApplication.translate("MainWindow", u"Financeiro", None))
        self.menuConsultas.setTitle(QCoreApplication.translate("MainWindow", u"Consultas", None))
        self.menuVendas.setTitle(QCoreApplication.translate("MainWindow", u"Vendas", None))
        self.menuConsumos.setTitle(QCoreApplication.translate("MainWindow", u"Consumos", None))
    # retranslateUi

