# Generated by Django 5.2.7 on 2025-10-28 23:10

import escola.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_alter_curso_codigo_alter_curso_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='celular',
            field=models.CharField(max_length=14, validators=[escola.validators.validate_celular]),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[escola.validators.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='nome',
            field=models.CharField(max_length=100, validators=[escola.validators.validate_nome]),
        ),
    ]
